//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LerrAzureDemo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VogelDTO", Namespace="http://schemas.datacontract.org/2004/07/LerrAzureServiceDemo")]
    [System.SerializableAttribute()]
    public partial class VogelDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVogel")]
    public interface IVogel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVogel/GetBirds", ReplyAction="http://tempuri.org/IVogel/GetBirdsResponse")]
        LerrAzureDemo.ServiceReference1.VogelDTO[] GetBirds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVogel/GetBirds", ReplyAction="http://tempuri.org/IVogel/GetBirdsResponse")]
        System.Threading.Tasks.Task<LerrAzureDemo.ServiceReference1.VogelDTO[]> GetBirdsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVogelChannel : LerrAzureDemo.ServiceReference1.IVogel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VogelClient : System.ServiceModel.ClientBase<LerrAzureDemo.ServiceReference1.IVogel>, LerrAzureDemo.ServiceReference1.IVogel {
        
        public VogelClient() {
        }
        
        public VogelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VogelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VogelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VogelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LerrAzureDemo.ServiceReference1.VogelDTO[] GetBirds() {
            return base.Channel.GetBirds();
        }
        
        public System.Threading.Tasks.Task<LerrAzureDemo.ServiceReference1.VogelDTO[]> GetBirdsAsync() {
            return base.Channel.GetBirdsAsync();
        }
    }
}
